### ISSUE TITLE
Registrierung schlägt fehl

### ISSUE THREAD

**Issue by pselsa** [thomashackl/contact-tracer#3]
Auf unserem Testsystem kann man sich nicht registrieren, offenbar fehlt im QR Code die Termin-ID.

Link aus QR Code:
https://studip-web3.elsa.uni-hannover.de/plugins.php/contacttracer/coursetracer/register/?cid=1e0a31c4ec1baea22fcbf062b3751831&again=yes

Passiert bei einem manuell angelegten Einzeltermin.

> Typ: Error
Nachricht: Call to a member function getRoom() on null
Code: 0
Stack trace:
#$ public/plugins_packages/upa/ContactTracer/controllers/coursetracer.php(150)
#0 vendor/trails/trails.php(557): CoursetracerController->register_action('')
#1 app/controllers/studip_controller.php(117): Trails_Controller->perform('register/')
#2 vendor/trails/trails.php(154): StudipController->perform('register/')
#3 vendor/trails/trails.php(121): Trails_Dispatcher->map_uri_to_response('coursetracer/re...')
#4 public/plugins_packages/upa/ContactTracer/ContactTracer.php(117): Trails_Dispatcher->dispatch('coursetracer/re...')
#5 public/plugins.php(54): ContactTracer->perform('coursetracer/re...')
#6 {main}

**Comment by pselsa** [comment]
Läuft, danke.
